{************************************************}
{                                                }
{  Copyright (C) MarinovSoft 2013-2014           }
{                                                }
{  http://marinovsoft.narod.ru                   }
{  mailto:super386@rambler.ru                    }
{                                                }
{************************************************}
{$ifdef fpc}
{$A1}
{$endif}

unit MSTConst;

interface

const
  cmAbout      = 170;
  cmReadDisc   = 171;
  cmWriteDisc  = 172;
  cmFormatDisc = 173;
  cmSelectDriveA = 174;
  cmSelectDriveB = 175;
  cmSelectDriveImage = 176;
  cmOptions    = 177;

  cmListDisk   = 178;
  cmView       = 179;
  cmDelete     = 13;

  cmCopyFileDOS = 180;
  cmCopyFileMST = 181;

Const
  kbGrayAst     = $372A;

implementation

end.
